[package]
name = "molecule-db"
version = "0.1.0"
edition = "2024"
rust-version = "1.95" # nixpkgs stable

[profile.dev.build-override]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
strip = true

[profile.release.build-override]
opt-level = 3

[lints.rust]
rust_2018_idioms = "deny"
unsafe_code = "forbid"
unstable_name_collisions = "allow"
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[features]
night = [
    "reqwest/blocking",
]
nixos = []

[build-dependencies]
gix = "0.87" # much slower than git2 but avoids a C dependency on openssl-sys
itertools = "0.15"
thiserror = "2"

[dependencies]
async-proto = "0.26"
base64 = "0.23"
bitstream-io = "4"
bitvec = { version = "1", default-features = false, features = ["atomic"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
collect-mac = "0.1"
enum-iterator = "2"
gix = { version = "0.87", features = ["blocking-http-transport-reqwest"] }
gophermap = "0.1"
http = "1"
itermore = { version = "0.8", features = ["array_combinations_with_reps", "array_windows"] }
itertools = "0.15"
lazy-regex = "3"
log-lock = { git = "https://github.com/fenhl/log-lock" }
mediawiki = { version = "0.5", default-features = false }
mimalloc = "0.1"
nonempty-collections = "1"
omsim-rs = { git = "https://github.com/fenhl/omsim-rs" }
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["charset", "form", "gzip", "hickory-dns", "http2", "rustls-no-provider", "system-proxy", "zstd"] }
rocket = { git = "https://github.com/fenhl/Rocket", branch = "forms", features = ["json"] }
rocket-util = { git = "https://github.com/fenhl/rocket-util" }
roman-numerals = "0.4"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "process", "rt"] }
url = { version = "2", features = ["serde"] }
wheel = { git = "https://github.com/fenhl/wheel", features = ["reqwest", "rocket", "serde_json"] }
xdg = "3"

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
directories = "6"
