[package]
name = "molecule-db"
version = "0.1.0"
edition = "2024"
rust-version = "1.91" # nixpkgs stable

[profile.dev.build-override]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
strip = true

[profile.release.build-override]
opt-level = 3

[lints.rust]
rust_2018_idioms = "deny"
unsafe_code = "forbid"
unstable_name_collisions = "allow"
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[build-dependencies]
gix = "0.83" # much slower than git2 but avoids a C dependency on openssl-sys
itertools = "0.14"
thiserror = "2"

[dependencies]
async-proto = "0.26"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
collect-mac = "0.1"
enum-iterator = "2"
gix = { version = "0.83", features = ["blocking-http-transport-reqwest"] }
itertools = "0.14"
mimalloc = "0.1"
omsim-rs = { git = "https://github.com/fenhl/omsim-rs" }
reqwest = { version = "0.13", default-features = false, features = ["rustls-no-provider"] }
rocket = { version = "0.5", features = ["json"] }
rocket-util = { git = "https://github.com/fenhl/rocket-util" }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["process"] }
wheel = { git = "https://github.com/fenhl/wheel", features = ["rocket"] }

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
directories = "6"
