use std::fmt;

macro_rules! puzzles {
    ($($name:literal, $variant:ident, $url:expr,)*) => {
        #[derive(Clone, Copy)]
        pub(crate) enum Puzzle {
            $($variant,)*
        }

        impl Puzzle {
            pub(crate) fn as_str(&self) -> &'static str {
                match self {
                    $(Self::$variant => $name,)*
                }
            }

            pub(crate) fn url(&self) -> Option<&'static str> {
                match self {
                    $(Self::$variant => $url,)*
                }
            }
        }
    };
}

impl Puzzle {
    pub(crate) fn is_custom(&self) -> bool {
        self.url().is_some()
    }
}

impl fmt::Display for Puzzle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_str().fmt(f)
    }
}

puzzles! {
    "A Welcome to House Colvan", AWelcomeToHouseColvan, Some("https://drive.google.com/drive/folders/1Lk1kj1YERh0yWvgIK89dpd_L7TzLhhTo"),
    "Ablative Crystal", AblativeCrystal, None,
    "Abrasive Particles", AbrasiveParticles, None,
    "Active Polymerase", ActivePolymerase, Some("https://reddit.com/r/opus_magnum/comments/fe8l4r/week_6_active_polymerase/"),
    "Aether Detector", AetherDetector, None,
    "Aether Reactor", AetherReactor, Some("https://events.critelli.technology/Week_5_AetherReactor"),
    "Airship Fuel", AirshipFuel, None,
    "Alchemical Jewel", AlchemicalJewel, None,
    "Alchemical Slag", AlchemicalSlag, None,
    "Alcohol Separation", AlcoholSeparation, None,
    "Amalgamated Gold Ring", AmalgamatedGoldRing, Some("https://reddit.com/r/opus_magnum/comments/ewj8ml/tournament_week_2_amalgamated_gold_ring/"),
    "Animismus Buffer", AnimismusBuffer, None,
    "Armor Filament", ArmorFilament, None,
    "Arquerite Promotion", ArqueritePromotion, Some("https://discord.com/channels/278707932089155584/296373951800541186/857072161097515049"),
    "Artificial Ore", ArtificialOre, Some("https://discord.com/channels/278707932089155584/296373951800541186/879900850661769278"),
    "Asbestos", Asbestos, Some("https://events.critelli.technology/OM2025Weeklies6_Asbestos"),
    "Assassin's Filament", AssassinsFilament, None,
    "Berlo's Dualism", BerlosDualism, Some("https://events.critelli.technology/b2567dd6f278003b0048996f5de5b64f"),
    "Bicrystal Transceiver", BicrystalTransceiver, Some("https://events.critelli.technology/OM2023_W6_BicrystalTransceiver"),
    "Biosteel Filament", BiosteelFilament, Some("https://events.critelli.technology/OM2023_W4_BiosteelFilament"),
    "Black Powder", BlackPowder, Some("https://events.critelli.technology/OM2023Weeklies_BlackPowder"),
    "Blood-Stanching Powder", BloodStanchingPowder, None,
    "Blue Vitriol", BlueVitriol, Some("https://events.critelli.technology/bb94e99e5b9f4d14791f50e953e6f2bb"),
    "Boozesort", Boozesort, Some("https://events.critelli.technology/OM2025Weeklies8_Boozesort"),
    "Brazing Cathode", BrazingCathode, Some("https://events.critelli.technology/OM2022Weeklies_BrazingCathode"),
    "Breathable Fluid", BreathableFluid, Some("https://events.critelli.technology/OM2024Weeklies_BreathableFluid"),
    "Bulk Transmutation", BulkTransmutation, Some("https://events.critelli.technology/OM2025week6_Bulk_Transmutation"),
    "Buoyant Cable", BuoyantCable, None,
    "Burning Spirit of Saturn", BurningSpiritOfSaturn, Some("https://events.critelli.technology/d3f9ca519aacb2d782a5388098299acd"),
    "Calm Before the Storm", CalmBeforeTheStorm, Some("https://drive.google.com/drive/folders/1JVbrvF7dcTKmYN68eGlWhTryXy1TEnc8"),
    "Cancer Medicine", CancerMedicine, Some("https://events.critelli.technology/d40f1593c0731c9325dd5c5b9ed3db4b"),
    "Celestial Thread", CelestialThread, None,
    "Children's toys", ChildrensToys, Some("https://events.critelli.technology/f308e34f12f681c32580ee82d0c96c72"),
    "Chromatic Aberration", ChromaticAberration, Some("https://events.critelli.technology/26a4f980a1b475197735802f9cb75836"),
    "Climbing Rope Fiber", ClimbingRopeFiber, None,
    "Colvan Blue", ColvanBlue, Some("https://discord.com/channels/278707932089155584/296373951800541186/851990719530532864"),
    "Conductive Enamel", ConductiveEnamel, None,
    "Connect the Dots", ConnectTheDots, Some("https://reddit.com/r/opus_magnum/comments/eohzw1/opus_magnum_tournament_2020/"),
    "Cool Earrings", CoolEarrings, Some("https://events.critelli.technology/OM2023_WO_CoolEarrings"),
    "Corporate Waste Reduction", CorporateWasteReduction, Some("https://events.critelli.technology/88fed58ce6219be91a046e9a62a004c7"),
    "Courage Potion", CouragePotion, None,
    "Cranberry Glass", CranberryGlass, Some("https://discord.com/channels/278707932089155584/296373951800541186/864679286073720832"),
    "Creative Accounting", CreativeAccounting, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Crimson Crystal Bisection", CrimsonCrystalBisection, Some("https://discord.com/channels/278707932089155584/296373951800541186/867218205080158208"),
    "Critellium", Critellium, Some("https://events.critelli.technology/e8f14a0982aaacbb3254457e77c23a0b"),
    "Crystal Compression", CrystalCompression, Some("https://discord.com/channels/278707932089155584/296373951800541186/862141779825655818"),
    "Crystallized Air", CrystallizedAir, Some("https://events.critelli.technology/OM2025week5_Crystallized_Air"),
    "Cuprite", Cuprite, Some("https://events.critelli.technology/OM2022Weeklies_Cuprite"),
    "Cuquerite Promotion", CuqueritePromotion, Some("https://events.critelli.technology/af91511ae10c69e531d347ad8656e594"),
    "Curious Lipstick", CuriousLipstick, None,
    "Dark Matter Candidate", DarkMatterCandidate, Some("https://events.critelli.technology/OM2023Weeklies_DarkMatterCandidate"),
    "Deep-Fried Rocket Propellant", DeepFriedRocketPropellant, Some("https://events.critelli.technology/OM2024Weeklies_DeepFriedRocketPropellant"),
    "Deep-Fried Unstable Compound", DeepFriedUnstableCompound, Some("https://events.critelli.technology/OM2024Weeklies_BSides_DeepFriedUnstableCompound"),
    "Dehydrated Water", DehydratedWater, Some("https://events.critelli.technology/OM2022Weeklies_DehydratedWater"),
    "Dental Amalgam", DentalAmalgam, Some("https://events.critelli.technology/c3dda33075913461bebd7cd7c8759669"),
    "Destabilized Nature", DestabilizedNature, Some("https://events.critelli.technology/683142751f1988e34bb824ac9302ed20"),
    "Do You Remember", DoYouRemember, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Dwarven Fire Wine", DwarvenFireWine, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Dye Hard", DyeHard, Some("https://events.critelli.technology/OM2023Weeklies_DyeHard"),
    "Electrum Separation", ElectrumSeparation, None,
    "Elemental Comparator", ElementalComparator, Some("https://events.critelli.technology/OM2023_W8w_ElementalComparator"),
    "ElementalJewelSetting", ElementalJewelSetting, Some("https://drive.google.com/drive/folders/1P7fsijiuJTI-1LKrpT7IMn7nj2V5PAvC"),
    "Embalming Fluid", EmbalmingFluid, None,
    "Emergency Antidote", EmergencyAntidote, Some("https://drive.google.com/drive/folders/1SL0WExUVLu6_xsvZCA9z29PH6RuFBrBd"),
    "End Game", EndGame, Some("https://events.critelli.technology/OM2023_W0_EndGame"),
    "Ephemeral Matrix", EphemeralMatrix, Some("https://events.critelli.technology/5a5504a1f72574d23012a6458d1a29b1"),
    "Evil Ore", EvilOre, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Explorer's Salve", ExplorersSalve, None,
    "Explosive Finger Trap", ExplosiveFingerTrap, Some("https://discord.com/channels/278707932089155584/296373951800541186/874833948570689577"),
    "Explosive Logic Unit", ExplosiveLogicUnit, Some("https://drive.google.com/drive/folders/1A_GkcZV1fxMt3vII6qGsD_wX2ULzG8Ca"),
    "Explosive Phial", ExplosivePhial, None,
    "Explosive Victrite", ExplosiveVictrite, None,
    "Extraction from Sapa", ExtractionFromSapa, Some("https://events.critelli.technology/65f67bd69c877c6b90352dea6c440aa1"),
    "Eyedrops Of Irritation", EyedropsOfIrritation, Some("https://events.critelli.technology/OM2023Weeklies_EyedropsOfIrritation"),
    "Eyedrops of Revelation", EyedropsOfRevelation, None,
    "Face Powder", FacePowder, None,
    "Faero Filament", FaeroFilament, Some("https://events.critelli.technology/OM2024Weeklies_FaeroFilament"),
    "Ferrous Wheel", FerrousWheel, Some("https://discord.com/channels/278707932089155584/296373951800541186/869756148788625459"),
    "Film Crystal", FilmCrystal, Some("https://events.critelli.technology/Week_4_FilmCrystal"),
    "Flake Salt", FlakeSalt, Some("https://events.critelli.technology/Week_-1_FlakeSalt"),
    "Fragrant Powders", FragrantPowders, None,
    "Fulmination", Fulmination, Some("https://events.critelli.technology/Week_6_Fulmination"),
    "Galvanization", Galvanization, Some("https://events.critelli.technology/58aea7d6d7ba1b4e8b73d2219de0a8cc"),
    "General Anaesthetic", GeneralAnaesthetic, None,
    "Green Vitriol", GreenVitriol, Some("https://discord.com/channels/278707932089155584/296373951800541186/859612178902286376"),
    "Golden Thread", GoldenThread, None,
    "Habitability Detector", HabitabilityDetector, Some("https://events.critelli.technology/OM2023_W8_HabitabilityDetector"),
    "Hair Product", HairProduct, None,
    "Hangover Cure", HangoverCure, None,
    "Health Tonic", HealthTonic, None,
    "Hemisphere Change", HemisphereChange, Some("https://events.critelli.technology/af2bef37158400f2caf15403a1d3c687"),
    "Hexstabilized Salt", HexstabilizedSalt, None,
    "Hexstabilized Teuling's Mors", HexstabilizedTeulingsMors, Some("https://events.critelli.technology/OM2023Weeklies_HexstabilizedTeulingsMors"),
    "High Gloss Finish", HighGlossFinish, Some("https://reddit.com/r/opus_magnum/comments/fhui7x/week_7_high_gloss_finish/"),
    "Hydroponic Solution", HydroponicSolution, Some("https://events.critelli.technology/OM2023_W3_HydroponicSolution"),
    "Hyper-volatile Gas", HyperVolatileGas, None,
    "Horn Silver", HornSilver, Some("https://discord.com/channels/278707932089155584/296373951800541186/849437821918904350"),
    "Hot Ice", HotIce, Some("https://events.critelli.technology/OM2022Weeklies_HotIce"),
    "Hydrophobic Water", HydrophobicWater, Some("https://events.critelli.technology/om2025week1_Hydrophobic_Water"),
    "Icelandic Lava Salt", IcelandicLavaSalt, Some("https://events.critelli.technology/952a099fce7b49281d4b95f0f37dae8e"),
    "Ignition Cord", IgnitionCord, Some("https://events.critelli.technology/OM2022Weeklies_IgnitionCord"),
    "Improved Explosive Phial", ImprovedExplosivePhial, Some("https://drive.google.com/drive/folders/1aRi8dJIu7YPhikm-QXRboJybAr9ZlW0j"),
    "In Berlo's Basement", InBerlosBasement, Some("https://events.critelli.technology/66f74ef1aae21439a688b1cc54ca894c"),
    "In Loco Dispono", InLocoDispono, Some("https://events.critelli.technology/5b464528478f002ba6866f690bd01f40"),
    "Instant Mirror Coat", InstantMirrorCoat, Some("https://events.critelli.technology/OM2024Weeklies_InstantMirrorCoat"),
    "Invisible Ink", InvisibleInk, None,
    "Jewel Box", JewelBox, Some("https://events.critelli.technology/OM2025Weeklies1_JewelBox"),
    "Lambent II/IX", Lambent29, None,
    "Lambent LXVII", Lambent67, Some("https://events.critelli.technology/0c61ded553925ac6b6d567386c9982b8"),
    "Lamplight Gas", LamplightGas, None,
    "Latch-Hook Fireworks", LatchHookFireworks, Some("https://events.critelli.technology/638f26965e21b260086e1919b264eab5"),
    "Leave No Trace", LeaveNoTrace, Some("https://events.critelli.technology/Week_0_LeaveNoTrace"),
    "Lesson: Arms", LessonArms, None,
    "Lesson: Bonding", LessonBonding, None,
    "Lesson: Introduction", LessonIntroduction, None,
    "Lesson: Pistons", LessonPistons, None,
    "Lesson: Pivots", LessonPivots, None,
    "Lesson: Tracks", LessonTracks, None,
    "Lesson: Transmutation", LessonTransmutation, None,
    "Life-Sensing Potion", LifeSensingPotion, None,
    "Litharge Separation", LithargeSeparation, None,
    "Local Anaesthetic", LocalAnaesthetic, Some("https://events.critelli.technology/2414043fbe61ace7b2335186a998fcd8"),
    "Logistics", Logistics, Some("https://events.critelli.technology/d18b0ff75237478b9f7d27f799222e46"),
    "Look-And-Say", LookAndSay, Some("https://events.critelli.technology/OM2024Weeklies_LookAndSay"),
    "Lubricating Filament", LubricatingFilament, None,
    "Lubricating Solvents", LubricatingSolvents, Some("https://events.critelli.technology/Week_3_LubricatingSolvents"),
    "Lustre", Lustre, None,
    "Lustrous Syrup", LustrousSyrup, Some("https://events.critelli.technology/OM2022Weeklies_LustrousSyrup"),
    "Magistery of Saturn", MagisteryOfSaturn, Some("https://events.critelli.technology/9679227965273efecaca286dadb4dabf"),
    "Martial Regulus", MartialRegulus, Some("https://events.critelli.technology/OM2022Weeklies_MartialRegulus"),
    "Material Salvage", MaterialSalvage, Some("https://events.critelli.technology/om2025break_Material_Salvage"),
    "Memory Lane", MemoryLane, Some("https://events.critelli.technology/OM2025week8_Memory_Lane"),
    "Metal Calculus", MetalCalculus, Some("https://reddit.com/r/opus_magnum/comments/flp70t/the_final_week_of_the_tournament_metal_calculus/"),
    "Miraculous Autosalt", MiraculousAutosalt, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Mist of Dousing", MistOfDousing, Some("https://drive.google.com/drive/folders/1JX9JEdzXfFgn1-z4Yno_oMjSHHg8eGxE"),
    "Mist of Hallucination", MistOfHallucination, None,
    "Mist of Incapacitation", MistOfIncapacitation, None,
    "Moonlight Catalyst", MoonlightCatalyst, Some("https://events.critelli.technology/OM2025Weeklies11_MoonlightCatalyst"),
    "Nightmare Fuel", NightmareFuel, Some("https://events.critelli.technology/OM2022Weeklies_NightmareFuel"),
    "Nylon", Nylon, Some("https://events.critelli.technology/OM2025Weeklies9_Nylon"),
    "Ornamental Plating", OrnamentalPlating, Some("https://events.critelli.technology/OM2024Weeklies_OrnamentalPlating"),
    "Overloaded", Overloaded, Some("https://reddit.com/r/opus_magnum/comments/f7674d/week_5_overloaded/"),
    "Pousse-Café", PousseCafe, Some("https://events.critelli.technology/f883eb7701f420e1b1960eabe37b7fc1"),
    "Palatable Tissue", PalatableTissue, Some("https://events.critelli.technology/OM2024Weeklies_PalatableTissue"),
    "Panacea", Panacea, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Panacea to Poison", PanaceaToPoison, Some("https://drive.google.com/drive/folders/1-Ky7fk653U6Zr9bPgEzGDtI3QX7vVJlE"),
    "Parade-Rocket Fuel", ParadeRocketFuel, None,
    "Pareto Poppers", ParetoPoppers, Some("https://events.critelli.technology/OM2025Weeklies4_ParetoPoppers"),
    "Pass-Through Alloy", PassThroughAlloy, Some("https://events.critelli.technology/OM2025week7_Pass-Through_Alloy"),
    "Philosopher's Catalyst", PhilosophersCatalyst, Some("https://events.critelli.technology/OM2022Weeklies_PhiloCatalyst"),
    "Pitch Drop Experiment", PitchDropExperiment, Some("https://events.critelli.technology/OM2024Weeklies_PitchDropExperiment"),
    "Plastic", Plastic, Some("https://events.critelli.technology/ac6ab9dc43b0ac7ad9277c25ed5375e1"),
    "Potent Painkillers", PotentPainkillers, Some("https://events.critelli.technology/Week_7_PotentPainkillers"),
    "Potent Potables", PotentPotables, Some("https://reddit.com/r/opus_magnum/comments/et5lyo/tournament_week_1_potent_potables/"),
    "Precision Machine Oil", PrecisionMachineOil, None,
    "Preservative Salt", PreservativeSalt, None,
    "Probe Module", ProbeModule, Some("https://events.critelli.technology/OM2023_W5_ProbeModule"),
    "Proof of Completeness", ProofOfCompleteness, None,
    "Purified Gold", PurifiedGold, None,
    "Quintessential Aerogel", QuintessentialAerogel, Some("https://events.critelli.technology/OM2022Weeklies_QuintAerogel"),
    "Quintessential Catalyst", QuintessentialCatalyst, Some("https://discord.com/channels/278707932089155584/296373951800541186/877363315687436349"),
    "Quintessential Explosive", QuintessentialExplosive, Some("https://events.critelli.technology/OM2023Weeklies_QuintExplosive"),
    "Quintessential Medium", QuintessentialMedium, None,
    "Quintessential Stabilizer", QuintessentialStabilizer, Some("https://drive.google.com/drive/folders/1sommL5qdrN8fa0-D_dnwEJxVlwu34QgT"),
    "Radio Receivers", RadioReceivers, Some("https://events.critelli.technology/Week_8_RadioReceivers"),
    "Rat Poison", RatPoison, None,
    "Ravari's Rage", RavarisRage, Some("https://drive.google.com/drive/folders/1iy7KDmdkO4HGbjD1_jX_qb8mQ2IeSmS1"),
    "Ravari's Road", RavarisRoad, Some("https://events.critelli.technology/OM2025Weeklies7_RavarisRoad"),
    "Ravari's Wheel", RavarisWheel, None,
    "Reactive Cinnabar", ReactiveCinnabar, None,
    "Reactive Gold", ReactiveGold, None,
    "Recipe for Disaster", RecipeForDisaster, Some("https://events.critelli.technology/OM2025Weeklies10_RecipeForDisaster"),
    "Reconstructed Solvent", ReconstructedSolvent, None,
    "Refined Bronze", RefinedBronze, None,
    "Refined Gold", RefinedGold, None,
    "Resonant Crystal", ResonantCrystal, None,
    "Retro Refining", RetroRefining, Some("https://events.critelli.technology/OM2024Weeklies_RetroRefining"),
    "Ring Enlargement", RingEnlargement, Some("https://events.critelli.technology/OM2023Weeklies_RingEnlargement"),
    "Rocket Propellant", RocketPropellant, None,
    "Rust Removal", RustRemoval, Some("https://events.critelli.technology/Week_1_RustRemoval"),
    "Sailcloth Thread", SailclothThread, None,
    "Salt Packaging Factory", SaltPackagingFactory, Some("https://events.critelli.technology/OM2023Weeklies_SaltPackagingFactory"),
    "Salt of Saturn by Vinegar", SaltOfSaturnByVinegar, Some("https://events.critelli.technology/9cec1eb8ff25a6ee4c73c77176524146"),
    "Sand of Suspension", SandOfSuspension, Some("https://events.critelli.technology/OM2025Weeklies2_SandOfSuspension"),
    "Saturn's Tree", SaturnsTree, Some("https://events.critelli.technology/9358b0efab6c1f32b850f898b8b2a675"),
    "Scrap Metal", ScrapMetal, Some("https://events.critelli.technology/a1dcf5402132b1b4c28d63ef02942db8"),
    "Seal Solvent", SealSolvent, None,
    "Self-Organizing Fluid", SelfOrganizingFluid, Some("https://events.critelli.technology/OM2025week3_Self-Organizing_Fluid"),
    "Self-Pressurizing Gas", SelfPressurizingGas, Some("https://events.critelli.technology/OM2023_W1_SelfPressurizingGas"),
    "Servin's Wheel", ServinsWheel, Some("https://events.critelli.technology/OM2022Weeklies_ServinsWheel"),
    "Silver Apple of Discord", SilverAppleOfDiscord, Some("https://events.critelli.technology/3e07b2ebbabd5ea7e9b87f8cd35d679f"),
    "Silver Caustic", SilverCaustic, None,
    "Silver Paint", SilverPaint, None,
    "Simulacrum", Simulacrum, Some("https://events.critelli.technology/ff3f211965e5ba83ac8a080335ddd04e"),
    "Smog Neutralization", SmogNeutralization, Some("https://events.critelli.technology/OM2025Weeklies5_SmogNeutralization"),
    "Soothing Salve", SoothingSalve, Some("https://events.critelli.technology/Week_2_SoothingSalve"),
    "Sophick Mercury", SophickMercury, Some("https://events.critelli.technology/OM2024Weeklies_SophickMercury"),
    "Special Amaro", SpecialAmaro, None,
    "Spyglass Crystal", SpyglassCrystal, None,
    "Stabilized Everything", StabilizedEverything, Some("https://discord.com/channels/278707932089155584/296373951800541186/882448331119427604"),
    "Stabilized Gold", StabilizedGold, Some("https://events.critelli.technology/OM2022Weeklies_StabilizedGold"),
    "Stabilized Water", StabilizedWater, None,
    "Stain Remover", StainRemover, None,
    "Stamina Potion", StaminaPotion, None,
    "Superconductive Copper", SuperconductiveCopper, Some("https://discord.com/channels/278707932089155584/296373951800541186/854533289816358922"),
    "Surrender Flare", SurrenderFlare, None,
    "Suspiciously Stable Substance", SuspiciouslyStableSubstance, Some("https://events.critelli.technology/OM2022Weeklies_SSS"),
    "Suture Thread", SutureThread, None,
    "Sweeper Rod", SweeperRod, Some("https://events.critelli.technology/OM2022Weeklies_SweeperRod"),
    "Swamp Fiber", SwampFiber, Some("https://reddit.com/r/opus_magnum/comments/f05mp5/week_3_swamp_fiber/"),
    "Sword Alloy", SwordAlloy, None,
    "Synthesis via Alcohol", SynthesisViaAlcohol, None,
    "Synthetic Malachite", SyntheticMalachite, None,
    "Taricene", Taricene, Some("https://events.critelli.technology/21042bbbbef69aef2000df9b97a4df9b"),
    "The Amazing Everything-Machine", TheAmazingEverythingMachine, Some("https://events.critelli.technology/OM2025week4_The_Amazing_Everything-Machine"),
    "Thermal Fuse", ThermalFuse, Some("https://events.critelli.technology/d3689000418b9687654554f28324d8d0"),
    "Thermic Capacitor", ThermicCapacitor, Some("https://events.critelli.technology/om2025week2_Thermic_Capacitor"),
    "Thermite Tape", ThermiteTape, Some("https://events.critelli.technology/OM2025Weeklies3_ThermiteTape"),
    "Timing Crystal", TimingCrystal, None,
    "Tinsel", Tinsel, Some("https://events.critelli.technology/bf33acfc5ce6933ae39b8ee5deb663af"),
    "Tonic of Hydration", TonicOfHydration, None,
    "Tonic of Transmogrification", TonicOfTransmogrification, Some("https://events.critelli.technology/OM2023Weeklies_TransTonic"),
    "Touch Grass", TouchGrass, Some("https://events.critelli.technology/OM2024Weeklies_TouchGrass"),
    "Touchstone", Touchstone, Some("https://events.critelli.technology/6f37903681423b320da82fb57900291d"),
    "Transmutation CX", Transmutation110, Some("https://events.critelli.technology/Week_9_TransmutationCX"),
    "Universal Compound", UniversalCompound, None,
    "Universal Solvent", UniversalSolvent, None,
    "Unstable Compound", UnstableCompound, None,
    "Unstable Sovrium", UnstableSovrium, Some("https://events.critelli.technology/OM2024Weeklies_UnstableSovrium"),
    "Unwinding", Unwinding, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Vaccine Template", VaccineTemplate, Some("https://events.critelli.technology/5d936a1ca336f6658f097260eda56a8f"),
    "Van Berlo's Chain", VanBerlosChain, None,
    "Van Berlo's Pivots", VanBerlosPivots, None,
    "Van Berlo's Wheel", VanBerlosWheel, None,
    "Vanishing Material", VanishingMaterial, None,
    "Vapor of Levity", VaporOfLevity, None,
    "Vaporized Propellant", VaporizedPropellant, Some("https://discord.com/channels/278707932089155584/296373951800541186/872298625798119455"),
    "Vaporous Solvent", VaporousSolvent, None,
    "Very Dark Thread", VeryDarkThread, None,
    "Virulent Vector", VirulentVector, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Viscous Adhesive", ViscousAdhesive, Some("https://events.critelli.technology/OM2023Weeklies_ViscousAdhesive"),
    "Viscous Sludge", ViscousSludge, None,
    "Visillary Anaesthetic", VisillaryAnaesthetic, None,
    "Volatility and Tranquility", VolatilityAndTranquility, Some("https://reddit.com/r/opus_magnum/comments/f3n89y/week_4_volatility_and_tranquility/"),
    "Voltaic Coil", VoltaicCoil, None,
    "Wakefulness Potion", WakefulnessPotion, None,
    "Warming Tonic", WarmingTonic, None,
    "Warp Fuel", WarpFuel, Some("https://events.critelli.technology/OM2023_W7_WarpFuel"),
    "Waste Reclamation", WasteReclamation, Some("https://events.critelli.technology/OM2023_W2_WasteReclamation"),
    "Water Purifier", WaterPurifier, None,
    "Waterproof Sealant", WaterproofSealant, None,
    "Welding Thermite", WeldingThermite, None,
    "Wheel Inversion", WheelInversion, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
    "Wheel Representation", WheelRepresentation, None,
    "Wire Forming and Unforming", WireFormingAndUnforming, Some("https://reddit.com/r/opus_magnum/comments/abpxj8/opus_magnum_tourney/"),
}
